### ISSUE TITLE
Type of Graph

### ISSUE THREAD

**Issue by brrbaral** [bd2kccd/PyTetrad#113]
Thanks for Pycausal. I am using pycausal in my custom dataset. The graph obtained are directed, undirected, bidirected, or uncertain types. Is there any way to specify to get only the directed graph as output?

**Comment by jdramsey** [comment]
Interesting. You know, we updated the underlying Tetrad jar that pycausal
uses, but pycausal is not configured for the update, mainly because the
person who had put pycausal together is no longer with us. I have a
replacement script that allows you to run Tetrad algorithms in Python.
Would you be interested?

Also, what algorithm(s) are you using?

**Comment by jdramsey** [comment]
Also, what are the dimensions of your dataset? (I'm slowly learning not to
ask too many questions when someone says they have a "custom" dataset. :))

**Comment by brrbaral** [comment]
Thank Your @jdramsey

**Comment by jdramsey** [comment]
@brrbaral I assume you don't need this, since you closed the issue. If you do, find me online and send me an email.
